### ISSUE TITLE
Add python script that Sends OS notification when limit about to exhaust limit

### ISSUE THREAD

**Issue by rhnvrm** [rhnvrm/snu-data-limit#5]

**Comment by mr-karan** [comment]
It's super simple with pynotify

check https://github.com/mr-karan/quoteNotify/blob/master/notify.py#L6

**Comment by rhnvrm** [comment]
I guess it'll now just be better to add a new feature that logs you out
automatically using the chrome extension say, every X hours and sends a
notification using the extension.

Further, since we get all the data about the usage, we can predict X by
calculating the velocity of data usage as well.

Sincerely,
Rohan Verma
hello@rohanverma.net
+91 9911296253
